#!/bin/bash
USER_DISTRIB="/home/dev/workspace/sivm-gen2-produit/third_party/generic3_ucineo"
USER_SYSROOT="$USER_DISTRIB/i586-generic3-linux-gnu/sysroot"
USER_PREFIX="$USER_SYSROOT/usr"
USER_PATH="$USER_SYSROOT/usr/bin"
# USER_CPP="$USER_DISTRIB/bin/i586-generic3-linux-gnu-cpp"
USER_CC="$USER_DISTRIB/bin/i586-generic3-linux-gnu-gcc"
USER_CXX="$USER_DISTRIB/bin/i586-generic3-linux-gnu-g++"
USER_LD="$USER_DISTRIB/bin/i586-generic3-linux-gnu-ld"
# USER_CPPFLAGS="--sysroot=$USER_SYSROOT"
USER_CUSTOM_CFLAGS="--sysroot=$USER_SYSROOT -m32"
USER_CUSTOM_CXXFLAGS="--sysroot=$USER_SYSROOT -m32 -Wno-shadow"
USER_PKG_CONFIG_DIR=""
USER_PKG_CONFIG_LIBDIR="$USER_SYSROOT/usr/lib/pkgconfig:$USER_SYSROOT/usr/share/pkgconfig"
USER_PKG_CONFIG_SYSROOT_DIR="$USER_SYSROOT"
USER_BUILD="pc-linux-gnu"
USER_HOST="i586"
USER_TARGET="$USER_DISTRIB/i586-generic3-linux-gnu"
USER_JOBS='8'
USER_INPUT_PLUGINS='sqlite'
USER_BOOST_INCLUDES="$USER_SYSROOT/usr/include"
USER_BOOST_LIBS="$USER_SYSROOT/usr/lib"
USER_BINDINGS='none'
USER_PNG='True'
USER_PNG_INCLUDES="$USER_SYSROOT/usr/include"
USER_PNG_LIBS="$USER_SYSROOT/usr/lib"
USER_JPEG='False'
USER_TIFF='False'
USER_WEBP='False'
USER_PROJ='True'
USER_GRID_RENDERER='False'
USER_CPP_TESTS='False'
USER_SHAPE_MEMORY_MAPPED_FILE='False'
USER_FRAMEWORK_PYTHON='False'
USER_PYTHON_DYNAMIC_LOOKUP='False'
USER_SHAPEINDEX='False'
USER_FREETYPE_CONFIG="$USER_SYSROOT/usr/bin/freetype-config"
USER_XML2_CONFIG="$USER_SYSROOT/usr/bin/xml2-config"
USER_SQLITE_INCLUDES="$USER_SYSROOT/usr/include/"
USER_SQLITE_LIBS="$USER_SYSROOT/usr/lib/"
USER_ICU_INCLUDES="$USER_SYSROOT/usr/include/"
USER_ICU_LIBS="$USER_SYSROOT/usr/lib/"
USER_CAIRO_LIBS="$USER_SYSROOT/usr/lib"
USER_CAIRO_INCLUDES="$USER_SYSROOT/usr/include"
USER_ICU_INCLUDES="$USER_SYSROOT/usr/include"
USER_ICU_LIBS="$USER_SYSROOT/usr/lib"
USER_PROJ_INCLUDES="$USER_SYSROOT/usr/include"
USER_PROJ_LIBS="$USER_SYSROOT/usr/lib"
USER_HB_INCLUDES="$USER_SYSROOT/usr/include"
USER_HB_LIBS="$USER_SYSROOT/usr/lib"

./configure DISTRIB="$USER_DISTRIB" SYSROOT="$USER_SYSROOT" PREFIX="$USER_PREFIX" PATH="$USER_PATH" CC="$USER_CC" CXX="$USER_CXX" LD="$USER_LD" CUSTOM_CFLAGS="$USER_CUSTOM_CFLAGS" CUSTOM_CXXFLAGS="$USER_CUSTOM_CXXFLAGS" PKG_CONFIG_DIR="$USER_PKG_CONFIG_DIR" PKG_CONFIG_LIBDIR="$USER_PKG_CONFIG_LIBDIR" PKG_CONFIG_SYSROOT_DIR="$USER_PKG_CONFIG_SYSROOT_DIR" BUILD="$USER_BUILD" HOST="$USER_HOST" TARGET="$USER_TARGET" JOBS="$USER_JOBS" INPUT_PLUGINS="$USER_INPUT_PLUGINS" BOOST_INCLUDES="$USER_BOOST_INCLUDES" BOOST_LIBS="$USER_BOOST_LIBS" BINDINGS="$USER_BINDINGS" PNG="$USER_PNG" PNG_INCLUDES="$USER_PNG_INCLUDES" PNG_LIBS="$USER_PNG_LIBS" JPEG="$USER_JPEG" TIFF="$USER_TIFF" WEBP="$USER_WEBP" PROJ="$USER_PROJ" GRID_RENDERER="$USER_GRID_RENDERER" CPP_TESTS="$USER_CPP_TESTS" SHAPE_MEMORY_MAPPED_FILE="$USER_SHAPE_MEMORY_MAPPED_FILE" FRAMEWORK_PYTHON="$USER_FRAMEWORK_PYTHON" PYTHON_DYNAMIC_LOOKUP="$USER_PYTHON_DYNAMIC_LOOKUP" SHAPEINDEX="$USER_SHAPEINDEX" FREETYPE_CONFIG="$USER_FREETYPE_CONFIG" XML2_CONFIG="$USER_XML2_CONFIG" SQLITE_INCLUDES="$USER_SQLITE_INCLUDES" SQLITE_LIBS="$USER_SQLITE_LIBS" ICU_INCLUDES="$USER_ICU_INCLUDES" ICU_LIBS="$USER_ICU_LIBS" CAIRO_LIBS="$USER_CAIRO_LIBS" CAIRO_INCLUDES="$USER_CAIRO_INCLUDES" ICU_INCLUDES="$USER_ICU_INCLUDES" ICU_LIBS="$USER_ICU_LIBS" PROJ_INCLUDES="$USER_PROJ_INCLUDES" PROJ_LIBS="$USER_PROJ_LIBS" HB_INCLUDES="$USER_HB_INCLUDES" HB_LIBS="$USER_HB_LIBS" $@
make