#!/bin/bash

USER_PREFIX="/usr/local/"
USER_JOBS='8'
USER_INPUT_PLUGINS='sqlite'
USER_BINDINGS='none'
USER_PNG='True'
USER_JPEG='False'
USER_TIFF='False'
USER_WEBP='False'
USER_PROJ='False'
USER_GRID_RENDERER='False'
USER_CPP_TESTS='False'
USER_SHAPE_MEMORY_MAPPED_FILE='False'
USER_FRAMEWORK_PYTHON='False'
USER_PYTHON_DYNAMIC_LOOKUP='False'
USER_SHAPEINDEX='False'
USER_BOOST_INCLUDES="/usr/local/include"
USER_BOOST_LIBS="/usr/local/lib"

./configure PREFIX="$USER_PREFIX" JOBS="$USER_JOBS" INPUT_PLUGINS="$USER_INPUT_PLUGINS" BINDINGS="$USER_BINDINGS" PNG="$USER_PNG" JPEG="$USER_JPEG" TIFF="$USER_TIFF" WEBP="$USER_WEBP" PROJ="$USER_PROJ" GRID_RENDERER="$USER_GRID_RENDERER" CPP_TESTS="$USER_CPP_TESTS" SHAPE_MEMORY_MAPPED_FILE="$USER_SHAPE_MEMORY_MAPPED_FILE" FRAMEWORK_PYTHON="$USER_FRAMEWORK_PYTHON" PYTHON_DYNAMIC_LOOKUP="$USER_PYTHON_DYNAMIC_LOOKUP" SHAPEINDEX="$USER_SHAPEINDEX" BOOST_INCLUDES="$USER_BOOST_INCLUDES" BOOST_LIBS="$USER_BOOST_LIBS" $@
make
